"use client";

// Interactive Leaflet map of Kingston parking: color-coded street overlay
// (every public street in the UGA), zone polygons/label chips, ATMs, and the
// UGA boundary. Leaflet touches `window` at module scope, so it is imported
// dynamically inside useEffect — this component renders an empty shell on
// the server and hydrates on the client. Leaflet CSS is global.
//
// Street geometry lives in /geo/street-parking.json (generated by
// scripts/gen-street-parking.py from OSM + the Census Kingston CDP boundary)
// and is fetched at runtime so the JS bundle stays lean.
//
// Zones with polygons render as filled polygons only (no marker bubbles —
// owner feedback). Zones without polygons get a compact white label chip
// (L.divIcon) with a colored left border keyed to the rule. Port-area
// polygons carry permanent name tooltips that appear at zoom >= 17.
//
// Street View: every popup gets a free deep link (no API key). If
// NEXT_PUBLIC_GMAPS_EMBED_KEY is set, clicking a feature also opens an
// embedded Street View panel below the map (Maps Embed API — free tier).
//
// Default Leaflet marker icons are deliberately NOT used (their asset paths
// break under bundlers). Colors here are intentionally hex — they live on
// the map canvas, not in the page's token system.

import { useEffect, useRef, useState } from "react";
import type { LatLngBounds, Map as LeafletMap } from "leaflet";
import type { MapZone } from "@/lib/data/parking";
import type { Atm } from "@/lib/types";

// Rule → color, keyed by string so new rules added to the data layer
// (e.g. "load-zone", "permit") render sensibly without a type-level
// dependency on parking.ts's ParkingRule union.
const RULE_COLORS: Record<string, string> = {
  "free-2hr": "#2e9e4f",
  "free-unrestricted": "#1E96C0",
  paid: "#7c4dbe",
  "park-and-ride-24h": "#e8891d",
  prohibited: "#d43d3d",
  "load-zone": "#f0b429",
  permit: "#6b7280",
};
const FALLBACK_RULE_COLOR = "#6b7280";

function ruleColor(rule: string): string {
  return RULE_COLORS[rule] ?? FALLBACK_RULE_COLOR;
}

type StreetRule =
  | "free-2hr"
  | "free-unrestricted"
  | "prohibited"
  | "ferry-holding"
  | "default";

const STREET_COLORS: Record<StreetRule, string> = {
  "free-2hr": "#2e9e4f",
  "free-unrestricted": "#1E96C0",
  prohibited: "#d43d3d",
  "ferry-holding": "#64748b",
  default: "#8b9aa8",
};

const STREET_RULE_LABELS: Record<StreetRule, string> = {
  "free-2hr": "Free street parking · 2-hour limit",
  "free-unrestricted": "Free street parking · no time limit",
  prohibited: "No street parking",
  "ferry-holding":
    "Ferry holding corridor — this is the line for the boat, not street parking",
  default: "No known restriction — free where unsigned",
};

function normalizeStreetRule(rule: string): StreetRule {
  return rule in STREET_COLORS ? (rule as StreetRule) : "default";
}

/** Line style per street rule. Prohibited stays red but muted; the ferry
 *  holding corridor is a quiet dashed slate — it's the boat line, not a
 *  parking hazard to shout about. */
function streetStyle(rule: StreetRule): {
  color: string;
  weight: number;
  opacity: number;
  dashArray?: string;
} {
  switch (rule) {
    case "ferry-holding":
      return { color: STREET_COLORS[rule], weight: 3, opacity: 0.45, dashArray: "4 6" };
    case "prohibited":
      return { color: STREET_COLORS[rule], weight: 4, opacity: 0.6 };
    case "free-2hr":
    case "free-unrestricted":
      return { color: STREET_COLORS[rule], weight: 6, opacity: 0.85 };
    default:
      return { color: STREET_COLORS.default, weight: 3, opacity: 0.5 };
  }
}

const ATM_COLOR = "#16405e"; // dark navy
const BOUNDARY_COLOR = "#324A6D";

interface StreetSegment {
  name: string;
  rule: string;
  coords: [number, number][];
  note?: string;
}

interface StreetData {
  boundary: [number, number][];
  segments: StreetSegment[];
}

const EMBED_KEY = process.env.NEXT_PUBLIC_GMAPS_EMBED_KEY;

// Permanent zone-name tooltips only appear once you're zoomed close enough
// for them to be useful; the class toggle happens on 'zoomend'.
const ZONE_LABEL_ZOOM = 17;

const MAP_CSS = `
.leaflet-container:not(.show-zone-labels) .zone-label { display: none; }
.leaflet-container .zone-label {
  background: rgba(255, 255, 255, 0.92);
  border: none;
  border-radius: 4px;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.25);
  color: #1f2933;
  font: 600 10px/1.2 system-ui, sans-serif;
  padding: 1px 5px;
}
.leaflet-container .zone-label::before { display: none; }
.zone-chip { background: transparent; border: none; }
`;

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Short text for the compact label chip of a marker-only zone: a short
 *  ALL-CAPS code from the name if present (e.g. "POKPARK"), else a terse
 *  rule word. */
const CHIP_TEXT: Record<string, string> = {
  paid: "P",
  "free-2hr": "2 HR",
  "free-unrestricted": "FREE",
  "park-and-ride-24h": "P&R",
  prohibited: "NO",
  "load-zone": "LOAD",
  permit: "PERMIT",
};

function chipText(zone: MapZone): string {
  const code = zone.name.match(/\(([A-Z0-9&+-]{2,8})\)/);
  if (code) return code[1];
  return CHIP_TEXT[zone.rule] ?? "P";
}

/** Compact display name for permanent zone tooltips. */
function zoneShortLabel(zone: MapZone): string {
  const code = zone.name.match(/\(([A-Z0-9&+-]{2,8})\)/);
  if (code) return code[1];
  const trimmed = zone.name
    .replace(/^Port (of Kingston )?/i, "")
    .replace(/\s*—.*$/, "")
    .trim();
  return trimmed.charAt(0).toUpperCase() + trimmed.slice(1);
}

function overnightLine(zone: MapZone): string {
  if (zone.overnight === "yes") return "Overnight: OK";
  if (zone.overnight === "no") return "Overnight: No";
  return zone.id.startsWith("port-")
    ? "Overnight: Call the Port office first — 360-297-3545"
    : "Overnight: Confirm on-site first";
}

function directionsUrl(lat: number, lng: number): string {
  return `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}&travelmode=driving`;
}

/** Free Google Street View deep link — opens the panorama nearest the point. */
function streetViewUrl(lat: number, lng: number): string {
  return `https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=${lat},${lng}`;
}

function linksRow(lat: number, lng: number, sourceUrl?: string): string {
  const links = [
    `<a href="${esc(streetViewUrl(lat, lng))}" target="_blank" rel="noopener noreferrer">👁 Street View</a>`,
    `<a href="${esc(directionsUrl(lat, lng))}" target="_blank" rel="noopener noreferrer">Directions</a>`,
  ];
  if (sourceUrl) {
    links.push(`<a href="${esc(sourceUrl)}" target="_blank" rel="noopener noreferrer">Source</a>`);
  }
  return `<p style="margin:6px 0 0;">${links.join(" · ")}</p>`;
}

function zonePopupHtml(zone: MapZone): string {
  const parts: string[] = [
    `<p style="margin:0;font-weight:600;font-size:0.95rem;">${esc(zone.name)}</p>`,
    `<p style="margin:4px 0 0;">${esc(zone.summary)}</p>`,
    `<p style="margin:4px 0 0;font-weight:600;">${esc(overnightLine(zone))}</p>`,
  ];
  if (zone.confidence !== "verified") {
    parts.push(
      `<p style="margin:4px 0 0;font-style:italic;">${esc(
        zone.sourceNote ?? "Per 2015 county study — obey posted signs."
      )}</p>`
    );
  }
  parts.push(linksRow(zone.center[0], zone.center[1], zone.sourceUrl));
  return `<div style="font-size:0.8rem;line-height:1.35;max-width:230px;">${parts.join("")}</div>`;
}

function streetPopupHtml(seg: StreetSegment, rule: StreetRule): string {
  const mid = seg.coords[Math.floor(seg.coords.length / 2)];
  // For the ferry corridor the rule IS the headline — lead with it and demote
  // the street name to the colored second line.
  const [title, subtitle] =
    rule === "ferry-holding"
      ? [STREET_RULE_LABELS[rule], seg.name]
      : [seg.name, STREET_RULE_LABELS[rule]];
  const parts: string[] = [
    `<p style="margin:0;font-weight:600;font-size:0.95rem;">${esc(title)}</p>`,
    `<p style="margin:4px 0 0;font-weight:600;color:${STREET_COLORS[rule]};">${esc(
      subtitle
    )}</p>`,
  ];
  if (seg.note) {
    parts.push(`<p style="margin:4px 0 0;">${esc(seg.note)}</p>`);
  }
  if (rule === "default") {
    parts.push(
      `<p style="margin:4px 0 0;font-style:italic;">Not field-surveyed — the sign on the pole always wins. State law tows vehicles left over 24 hours (RCW 46.55.085).</p>`
    );
  }
  parts.push(linksRow(mid[0], mid[1]));
  return `<div style="font-size:0.8rem;line-height:1.35;max-width:230px;">${parts.join("")}</div>`;
}

function atmPopupHtml(atm: Atm): string {
  const parts: string[] = [
    `<p style="margin:0;font-weight:600;font-size:0.95rem;">💵 ${esc(atm.name)}</p>`,
    `<p style="margin:4px 0 0;">${esc(atm.address)}</p>`,
    `<p style="margin:4px 0 0;">${esc(atm.feeNote)}</p>`,
    linksRow(atm.lat, atm.lng),
  ];
  return `<div style="font-size:0.8rem;line-height:1.35;max-width:230px;">${parts.join("")}</div>`;
}

interface SelectedSpot {
  name: string;
  lat: number;
  lng: number;
}

export function TownMap({
  zones = [],
  atms = [],
  showStreets = true,
  height = "460px",
  center = [47.7985, -122.4975],
  zoom = 15,
}: {
  zones?: MapZone[];
  atms?: Atm[];
  showStreets?: boolean;
  height?: string;
  center?: [number, number];
  zoom?: number;
}) {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<LeafletMap | null>(null);
  const boundaryBoundsRef = useRef<LatLngBounds | null>(null);
  const [selected, setSelected] = useState<SelectedSpot | null>(null);
  // On touch devices the map starts non-draggable so the page can scroll past
  // it; a tap unlocks panning. Always false on desktop (fine pointer).
  const [locked, setLocked] = useState(false);

  function unlock() {
    mapRef.current?.dragging.enable();
    setLocked(false);
  }

  useEffect(() => {
    let cancelled = false;

    (async () => {
      const L = (await import("leaflet")).default;
      // Guard: unmounted while loading, or already initialized (StrictMode).
      if (cancelled || !containerRef.current || mapRef.current) return;

      const map = L.map(containerRef.current, {
        center,
        zoom,
        scrollWheelZoom: false, // don't hijack page scroll; pinch/±-buttons still zoom
      });
      mapRef.current = map;

      // Touch devices: don't let a full-width map eat vertical page swipes.
      // Panning is disabled until the visitor taps to activate. Desktop
      // (fine pointer) stays fully interactive.
      const coarse =
        typeof window !== "undefined" &&
        window.matchMedia?.("(pointer: coarse)").matches;
      if (coarse) {
        map.dragging.disable();
        setLocked(true);
      } else {
        setLocked(false);
      }

      L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
        maxZoom: 19,
        attribution:
          '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
      }).addTo(map);

      // Permanent zone-name labels only past ZONE_LABEL_ZOOM — toggled with a
      // container class so the tooltips themselves never re-bind.
      const syncZoneLabels = () =>
        map
          .getContainer()
          .classList.toggle("show-zone-labels", map.getZoom() >= ZONE_LABEL_ZOOM);
      map.on("zoomend", syncZoneLabels);
      syncZoneLabels();

      // Street overlay + UGA boundary (fetched so the bundle stays lean).
      if (showStreets) {
        try {
          const res = await fetch("/geo/street-parking.json");
          if (res.ok && !cancelled && mapRef.current) {
            const data = (await res.json()) as StreetData;

            const boundaryLayer = L.polygon(data.boundary, {
              color: BOUNDARY_COLOR,
              weight: 2,
              dashArray: "6 6",
              fill: false,
              interactive: false,
            }).addTo(map);
            boundaryBoundsRef.current = boundaryLayer.getBounds();

            // Draw quiet layers first so rule-bearing streets sit on top:
            // default, then the muted ferry-holding corridor, then the rest.
            const rank = (r: StreetRule) =>
              r === "default" ? 0 : r === "ferry-holding" ? 1 : 2;
            const ordered = [...data.segments].sort(
              (a, b) =>
                rank(normalizeStreetRule(a.rule)) - rank(normalizeStreetRule(b.rule))
            );
            for (const seg of ordered) {
              const rule = normalizeStreetRule(seg.rule);
              const mid = seg.coords[Math.floor(seg.coords.length / 2)];
              L.polyline(seg.coords, streetStyle(rule))
                .addTo(map)
                .bindPopup(streetPopupHtml(seg, rule), { maxWidth: 260 })
                .on("click", () => setSelected({ name: seg.name, lat: mid[0], lng: mid[1] }));
            }
          }
        } catch {
          // Overlay is progressive enhancement — the base map still works.
        }
      }

      for (const zone of zones) {
        const color = ruleColor(zone.rule);
        const popup = zonePopupHtml(zone);
        const select = () =>
          setSelected({ name: zone.name, lat: zone.center[0], lng: zone.center[1] });
        if (zone.polygon && zone.polygon.length >= 3) {
          // Polygon zones render as the polygon alone — slightly stronger
          // fill so they read without a marker bubble on top.
          const layer = L.polygon(zone.polygon, {
            color,
            weight: 2,
            fillColor: color,
            fillOpacity: 0.45,
          })
            .addTo(map)
            .bindPopup(popup, { maxWidth: 260 })
            .on("click", select);
          // Port-area polygons get a permanent name label at close zoom
          // (visibility gated by the .show-zone-labels container class).
          if (zone.id.startsWith("port-")) {
            layer.bindTooltip(zoneShortLabel(zone), {
              permanent: true,
              direction: "center",
              className: "zone-label",
            });
          }
        } else {
          // No polygon: a compact label chip instead of a translucent bubble.
          const chip = L.divIcon({
            className: "zone-chip",
            html: `<span style="position:absolute;left:0;top:0;transform:translate(-50%,-50%);display:inline-block;background:#fff;border-left:2px solid ${color};border-radius:6px;padding:2px 6px;font:600 10px/1.2 system-ui,sans-serif;color:#1f2933;box-shadow:0 1px 3px rgba(0,0,0,0.25);white-space:nowrap;">${esc(
              chipText(zone)
            )}</span>`,
            iconSize: [0, 0],
            popupAnchor: [0, -12],
          });
          L.marker(zone.center, { icon: chip })
            .addTo(map)
            .bindPopup(popup, { maxWidth: 260 })
            .on("click", select);
        }
      }

      for (const atm of atms) {
        L.circleMarker([atm.lat, atm.lng], {
          radius: 5,
          color: "#ffffff",
          weight: 2,
          fillColor: ATM_COLOR,
          fillOpacity: 1,
        })
          .addTo(map)
          .bindTooltip(`💵 ${atm.name}`, { direction: "top", offset: [0, -6] })
          .bindPopup(atmPopupHtml(atm), { maxWidth: 260 })
          .on("click", () => setSelected({ name: atm.name, lat: atm.lat, lng: atm.lng }));
      }
    })();

    return () => {
      cancelled = true;
      mapRef.current?.remove();
      mapRef.current = null;
      boundaryBoundsRef.current = null;
    };
    // Data arrays and view options are static page data; re-running the effect
    // would tear the map down mid-interaction.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const goTo = (viewCenter: [number, number], viewZoom: number) => {
    mapRef.current?.setView(viewCenter, viewZoom);
  };

  const showWholeArea = () => {
    const map = mapRef.current;
    if (!map) return;
    if (boundaryBoundsRef.current) {
      map.fitBounds(boundaryBoundsRef.current, { padding: [12, 12] });
    } else {
      map.setView(center, 13);
    }
  };

  const quickViewButtonClass =
    "rounded-full border border-sand bg-white px-3 py-1 text-xs font-semibold text-sound-deep transition-colors hover:bg-shell";

  return (
    <div>
      <style>{MAP_CSS}</style>
      <div className="mb-2 flex flex-wrap gap-2">
        <button
          type="button"
          onClick={() => goTo([47.7985, -122.4975], 15)}
          className={quickViewButtonClass}
        >
          Downtown
        </button>
        <button
          type="button"
          onClick={() => goTo([47.7962, -122.4985], 18)}
          className={quickViewButtonClass}
        >
          Port parking
        </button>
        <button type="button" onClick={showWholeArea} className={quickViewButtonClass}>
          Whole area
        </button>
      </div>
      <div className="relative">
        <div
          ref={containerRef}
          style={{ height }}
          className="relative z-0 w-full overflow-hidden rounded-2xl border border-sand"
          role="region"
          aria-label="Map of Kingston street parking rules, lots, and ATMs"
        />
        {locked && (
          <button
            type="button"
            onClick={unlock}
            className="absolute inset-0 z-[450] flex items-end justify-center rounded-2xl bg-transparent pb-4"
            aria-label="Tap to interact with the map"
          >
            <span className="rounded-full bg-sound-deep/85 px-4 py-2 text-sm font-semibold text-white shadow">
              Tap to explore the map
            </span>
          </button>
        )}
      </div>
      {EMBED_KEY && selected && (
        <div className="mt-3 overflow-hidden rounded-2xl border border-sand">
          <div className="flex items-center justify-between bg-white px-4 py-2">
            <p className="text-sm font-semibold text-sound-deep">
              👁 Street View: {selected.name}
            </p>
            <button
              onClick={() => setSelected(null)}
              className="text-sm text-ink-soft hover:text-ink"
              aria-label="Close Street View"
            >
              ✕
            </button>
          </div>
          <iframe
            title={`Street View of ${selected.name}`}
            src={`https://www.google.com/maps/embed/v1/streetview?key=${EMBED_KEY}&location=${selected.lat},${selected.lng}&fov=90`}
            className="h-72 w-full border-0"
            loading="lazy"
            referrerPolicy="no-referrer-when-downgrade"
            allowFullScreen
          />
        </div>
      )}
      {!EMBED_KEY && selected && (
        <p className="mt-2 text-sm text-ink-soft">
          👁{" "}
          <a
            href={streetViewUrl(selected.lat, selected.lng)}
            target="_blank"
            rel="noopener noreferrer"
            className="font-medium text-tide-deep underline decoration-seaglass underline-offset-2"
          >
            Open Street View of {selected.name}
          </a>{" "}
          to see what the parking looks like.
        </p>
      )}
    </div>
  );
}

/** Color key for the map — render as a sibling right under <TownMap />. */
export function MapLegend({ showAtms = true }: { showAtms?: boolean }) {
  const zoneEntries: { color: string; label: string }[] = [
    { color: ruleColor("free-2hr"), label: "Zone: free 2-hr" },
    { color: ruleColor("paid"), label: "Paid lot" },
    { color: ruleColor("park-and-ride-24h"), label: "Park & ride · 24 hr" },
    { color: ruleColor("load-zone"), label: "Load zone" },
    { color: ruleColor("permit"), label: "Permit parking" },
  ];
  const streetEntries: { color: string; label: string }[] = [
    { color: STREET_COLORS["free-2hr"], label: "Street: free, 2-hr" },
    { color: STREET_COLORS["free-unrestricted"], label: "Street: free, no limit" },
    { color: STREET_COLORS.prohibited, label: "Street: no parking" },
    { color: STREET_COLORS.default, label: "Street: no known limit" },
  ];
  return (
    <ul className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-sm text-ink-soft">
      {streetEntries.map(({ color, label }) => (
        <li key={label} className="flex items-center gap-1.5">
          <span
            aria-hidden
            className="inline-block h-1 w-5 rounded-full"
            style={{ backgroundColor: color }}
          />
          {label}
        </li>
      ))}
      <li className="flex items-center gap-1.5">
        <span
          aria-hidden
          className="inline-block h-0 w-5 border-t-2 border-dashed"
          style={{ borderColor: STREET_COLORS["ferry-holding"] }}
        />
        Ferry holding line (queue for the boat)
      </li>
      {zoneEntries.map(({ color, label }) => (
        <li key={label} className="flex items-center gap-1.5">
          <span
            aria-hidden
            className="inline-block h-3 w-3 rounded-[3px]"
            style={{ backgroundColor: color }}
          />
          {label}
        </li>
      ))}
      <li className="flex items-center gap-1.5">
        <span
          aria-hidden
          className="inline-block h-0 w-5 border-t-2 border-dashed"
          style={{ borderColor: BOUNDARY_COLOR }}
        />
        Kingston UGA
      </li>
      {showAtms && (
        <li className="flex items-center gap-1.5">
          <span
            aria-hidden
            className="inline-block h-3 w-3 rounded-full ring-2 ring-white"
            style={{ backgroundColor: ATM_COLOR }}
          />
          ATM
        </li>
      )}
      <li className="w-full text-xs text-ink-soft/80">
        Tap any street or lot for rules and a Street View peek at the actual curb.
      </li>
    </ul>
  );
}
